export const quotesCategories = {
    simple: [
            "El sol brilla con fuerza en el cielo azul.",
            "La lluvia cae suavemente sobre el tejado.",
            "Los niños juegan felices en el parque.",
            "El café de la mañana sabe mejor caliente.",
            "Las flores del jardín están en plena primavera.",
            "Un buen libro es compañía para el alma.",
            "El pan recién horneado huele delicioso.",
            "La música suave relaja la mente ocupada.",
            "El viento mueve las hojas de los árboles.",
            "La luna llena ilumina la noche oscura.",
            "Caminar descalzo sobre la hierba fresca.",
            "El chocolate derretido es un placer único.",
            "Las olas del mar besan la orilla suavemente.",
            "El reloj marca las horas con precisión.",
            "Una sonrisa sincera abre cualquier puerta.",
            "El silbido del tren anuncia su llegada.",
            "El fuego crepita en la chimenea invernal.",
            "El queso añejo tiene un sabor intenso.",
            "La montaña se viste de blanco en invierno.",
            "El primer día de vacaciones siempre emociona.",
            "Las golondrinas vuelan en formación perfecta.",
            "El bosque guarda secretos milenarios.",
            "El despertador suena demasiado temprano.",
            "La miel dorada endulza cualquier momento.",
            "El camino serpentea entre colinas verdes.",
            "La abuela teje bufandas con amor infinito.",
            "El bebé duerme plácidamente en su cuna.",
            "El faro guía a los barcos en la oscuridad.",
            "La niebla cubre el valle al amanecer.",
            "El pan tostado cruje bajo la mantequilla.",
            "La bicicleta vieja tiene historias que contar.",
            "El espejo refleja una imagen familiar.",
            "La risa de los amigos cura el corazón.",
            "El viejo puente cruza el río con elegancia.",
            "La receta secreta lleva un toque especial.",
            "El cuaderno guarda pensamientos íntimos.",
            "La tormenta eléctrica asombra con su poder.",
            "El gato ronronea acurrucado en el sofá.",
            "La brújula señala siempre el norte verdadero.",
            "El perfume de jazmín inunda el jardín.",
            "La carretera vacía invita a viajar lejos.",
            "El abrazo cálido reconforta en días grises.",
            "La libélula se posa sobre el nenúfar.",
            "El quiosco vende periódicos y revistas.",
            "La bufanda gruesa protege del frío intenso.",
            "El mapa antiguo muestra rutas olvidadas.",
            "La taza favorita guarda memorias dulces.",
            "El columpio chirría en el patio vacío.",
            "La aurora boreal pinta cielos mágicos.",
            "El hojaldre crujiente deleita el paladar.",
            "La escalera de caracol sube hasta el ático.",
            "El silencio de la noche inspira paz interior.",
            "La caracola guarda el sonido del océano.",
            "El almuerzo familiar reúne generaciones.",
            "La luciérnaga brilla en la oscuridad.",
            "El cuadro colorido alegra la pared blanca.",
            "La llave antigua abre puertas misteriosas.",
            "El sendero pedregoso lleva a la cima.",
            "La barba del abuelo tiene canas sabias.",
            "El susurro del viento cuenta historias.",
            "La mermelada casera sabe a tradición.",
            "El paraguas rojo destaca bajo la lluvia.",
            "La sirena del barco resuena en el puerto.",
            "El mantel a cuadros cubre la mesa.",
            "La golosina favorita endulza la tarde.",
            "El pastor guía a sus ovejas al redil.",
            "La ventana abierta deja entrar brisas.",
            "El relámpago ilumina el cielo nocturno.",
            "La aldea dormida parece un cuadro vivo.",
            "El otoño tiñe las hojas de dorado.",
            "La fuente murmulla en la plaza central.",
            "El pastel de manzana huele a hogar.",
            "La bufanda tejida tiene colores vivos.",
            "El puñado de arena se escapa entre dedos.",
            "La mariposa monarca migra cada año.",
            "El farolillo ilumina el camino estrecho.",
            "La escalera de madera cruje al subir.",
            "El lago tranquilo refleja las nubes.",
            "La carreta cargada avanza lentamente.",
            "El aroma a tierra mojada es reconfortante.",
            "La bufanda de lana abriga en invierno.",
            "El viejo molino gira con el viento.",
            "La tetera silba anunciando el té listo.",
            "El puente colgante se mece suavemente.",
            "La cabaña de troncos parece acogedora.",
            "El racimo de uvas brilla con rocío.",
            "La fogata crepita bajo las estrellas.",
            "El desván guarda tesoros olvidados.",
            "La cometa vuela alto en cielos azules.",
            "El camino de tierra levanta polvo.",
            "La manta gruesa protege del frío.",
            "El bosque de pinos exhala frescura.",
            "La sirena de niebla alerta a los barcos.",
            "El atardecer pinta nubes anaranjadas.",
            "La montaña rusa emociona a los niños.",
            "El viejo pozo tiene historias de pueblo.",
            "La barca de remos flota en el lago.",
            "El horno de leña cocina pan dorado.",
            "La vereda empedrada lleva al mercado.",
            "El collar de perlas brilla elegantemente.",
            "La tormenta de nieve cubre los campos.",
            "El jardín zen invita a la meditación.",
            "La carpa del circo anuncia diversión.",
            "El camino rural serpentea entre campos.",
            "La tarta de cumpleaños tiene velas.",
            "El puente de piedra resiste el tiempo.",
            "La cabaña junto al río parece mágica.",
            "El colibrí liba néctar de las flores.",
            "La fogata nocturna une a las personas.",
            "El viejo telescopio descubre estrellas.",
            "La marea baja deja ver conchas marinas.",
            "El carrusel gira con música alegre.",
            "La almohada mullida invita a descansar.",
            "El sendero boscoso huele a tierra húmeda.",
            "La golondrina anida bajo el alero.",
            "El queso fundido gratinado es delicioso.",
            "La ventana empañada muestra dibujos.",
            "El camino de baldosas lleva al jardín.",
            "La sombrilla protege del sol abrasador.",
            "El río caudaloso arrastra hojas secas.",
            "La bufanda de seda ondea con el viento.",
            "El farol de gas alumbra calles antiguas.",
            "La escalinata de mármol parece interminable.",
            "El pastel de chocolate derretido tienta.",
            "La cabaña nevada parece de cuento.",
            "El puente de hierro cruza el valle.",
            "La tetera de porcelana es una reliquia.",
            "El camino ascendente desafía a caminantes.",
            "La flor de loto emerge del agua.",
            "El panal de abejas esconde dulzura.",
            "La linterna ilumina rincones oscuros.",
            "El sendero costero ofrece vistas al mar.",
            "La bufanda rayada combina con todo.",
            "El castillo en la colina inspira leyendas.",
            "La fuente de soda ofrece refrescos fríos.",
            "El camino de grava cruje bajo los pies.",
            "La rosa roja simboliza amor apasionado.",
            "El puente levadizo protege la fortaleza.",
            "La manta de patchwork tiene historia.",
            "El sendero de montaña exige esfuerzo.",
            "La taza de porcelana tiene dibujos finos.",
            "El bosque otoñal muestra colores vivos.",
            "La cabaña de pescador huele a redes.",
            "El camino iluminado guía a los viajeros.",
            "La flor de girasol sigue la luz solar.",
            "El puente de madera cruje al pasar.",
            "La tormenta de verano refresca el ambiente.",
            "El sendero junto al río es tranquilo.",
            "La bufanda de lana merino es cálida.",
            "El faro antiguo vigila acantilados rocosos."
    ],
    compleja: [
        "En el mundo actual, dominar la mecanografía no se limita a pulsar teclas rápidamente; es la capacidad de transcribir pensamientos complejos con fluidez, permitiendo que la mente se enfoque en la creatividad en lugar de la mecánica. La verdadera destreza surge cuando las manos adquieren memoria muscular, liberando al cerebro para tareas más elevadas.",
        "La vida es una sucesión de pequeños esfuerzos repetidos día tras día. Aquellos que perseveran descubren que los grandes logros no son más que la suma de acciones consistentes realizadas con determinación.",
        "Escribir sin pensar en cada letra permite al cerebro concentrarse en ideas más profundas, facilitando una conexión directa entre pensamiento y texto.",
        "Cuando la práctica se convierte en hábito, el progreso deja de ser una meta y se transforma en un camino natural que uno recorre con confianza.",
        "La mente clara y los dedos ágiles forman una dupla poderosa que convierte la mecanografía en un arte de precisión y fluidez.",
        "El verdadero dominio del teclado no se mide en palabras por minuto, sino en la armonía entre pensamiento, intención y ejecución.",
        "Cada sesión de práctica no solo mejora tu velocidad, sino que refuerza tu compromiso con la excelencia personal.",
        "No subestimes el poder de la repetición enfocada: es el secreto detrás de toda habilidad duradera.",
        "El viaje hacia la maestría en mecanografía está pavimentado con errores, correcciones y una inquebrantable voluntad de mejorar.",
        "Cuando los errores se interpretan como oportunidades, cada fallo se convierte en un peldaño hacia el éxito.",
        "La disciplina de sentarse cada día frente al teclado cultiva una actitud resiliente y metódica frente a cualquier reto.",
        "La escritura fluida nace cuando desaparece la conciencia de las teclas, y el pensamiento se materializa sin fricción.",
        "A veces el mayor progreso ocurre en silencio, cuando repites una frase por centésima vez sin perder la concentración.",
        "Las habilidades más valiosas se construyen con tiempo, paciencia y una pizca de terquedad positiva.",
        "Más que velocidad, busca consistencia: una base sólida permite crecer sin límites.",
        "Un error bien observado vale más que mil repeticiones sin atención.",
        "La práctica consciente transforma simples ejercicios en oportunidades de crecimiento personal.",
        "Escribir bien no es solo cuestión de dedos rápidos, sino de una mente entrenada en claridad y enfoque.",
        "Cada palabra bien escrita es un paso más hacia la confianza digital.",
        "Un teclado es como un instrumento musical: su dominio requiere oído, ritmo y práctica diaria.",
        "Cuando el cuerpo responde antes que la mente, es señal de que has internalizado el movimiento.",
        "Las herramientas digitales bien dominadas se convierten en extensiones naturales del pensamiento.",
        "La fluidez en la escritura digital abre puertas al aprendizaje, la creatividad y la expresión personal.",
        "El desarrollo de una habilidad técnica puede ser un camino espiritual si se recorre con conciencia y entrega.",
        "No hay nada trivial en aprender a escribir con precisión; cada letra es un acto de presencia.",
        "El progreso verdadero no se nota en un día, pero se hace evidente tras semanas de constancia.",
        "Dominar una habilidad es como plantar un árbol: los frutos llegan después de cuidado continuo.",
        "Cada minuto de práctica es una inversión silenciosa en tus capacidades futuras.",
        "Incluso los grandes escritores empezaron escribiendo lento y cometiendo errores.",
        "Una habilidad aprendida con atención perdura más allá de modas, dispositivos y contextos.",
        "La práctica diaria construye puentes entre lo que eres hoy y lo que puedes llegar a ser.",
        "El conocimiento sin práctica es como un libro sin abrir: su potencial permanece dormido.",
        "Cuando los dedos vuelan sobre el teclado sin esfuerzo, es porque muchas horas los entrenaron.",
        "No busques perfección inmediata: busca mejora constante.",
        "Cada sesión de escritura es también una sesión de entrenamiento mental.",
        "La repetición inteligente es el combustible del progreso sostenido.",
        "Al aprender mecanografía, no solo mejoras una habilidad, sino tu capacidad de atención.",
        "La precisión precede a la velocidad: primero hazlo bien, luego hazlo rápido.",
        "El aprendizaje efectivo combina intención clara, foco sostenido y retroalimentación honesta.",
        "Tu mente necesita silencio y estructura tanto como tus dedos necesitan agilidad.",
        "Desarrollar una habilidad técnica entrena también tu carácter.",
        "Cada tecla presionada con intención refuerza tu capacidad de actuar con propósito.",
        "Las grandes transformaciones comienzan con pequeños gestos repetidos con compromiso.",
        "El hábito no es enemigo de la creatividad: es su mejor aliado.",
        "Las habilidades digitales no son solo técnicas, son puertas al pensamiento y la expresión.",
        "Cuando escribes con soltura, tu pensamiento fluye sin obstáculos.",
        "Aprender una habilidad compleja te enseña también a aprender mejor.",
        "Escribir bien requiere algo más que práctica: requiere respeto por el proceso.",
        "El esfuerzo invisible detrás de cada línea escrita es lo que hace valiosa la fluidez.",
        "La mecanografía no es solo una herramienta: es una disciplina que fortalece la mente."    ],
    palabras: [
        "casa", "árbol", "montaña", "río", "cielo",
  "libro", "lápiz", "ventana", "silla", "mesa",
  "camino", "flor", "nube", "mariposa", "horizonte",
  "invierno", "verano", "otoño", "primavera", "amanecer",
  "atardecer", "familia", "amigo", "sonrisa", "sueño",
  "esperanza", "silencio", "melodía", "corazón", "viaje",
  "aventura", "recuerdo", "sorpresa", "jardín", "bosque",
  "océano", "playa", "arena", "estrella", "planeta",
  "universo", "misterio", "descubrimiento", "alegría", "tristeza",
  "éxito", "fracaso", "aprendizaje", "enseñanza", "curiosidad",
  "luz", "sombra", "piedra", "caminante", "historia",
  "futuro", "presente", "pasado", "mirada", "abrazo",
  "voz", "eco", "risa", "lluvia", "sol",
  "brisa", "noche", "día", "pájaro", "gato",
  "perro", "pez", "lago", "poesía", "cuento",
  "reloj", "puerta", "llave", "mundo", "ciudad",
  "pueblo", "campo", "semilla", "fruto", "manzana",
  "pan", "agua", "vino", "café", "camisa",
  "zapato", "retrato", "espejo", "canción", "tiempo",
  "llanto", "placer", "deseo", "temor", "energía",
  "movimiento", "pausa", "rutina", "realidad", "sombra",
  "hoja", "tronco", "raíz", "brazo", "pierna",
  "nariz", "ojo", "boca", "oreja", "cuello",
  "pared", "techo", "suelo", "teclado", "pantalla",
  "ratón", "teléfono", "cable", "internet", "correo",
  "mensaje", "voz", "palabra", "frase", "texto",
  "imagen", "foto", "color", "forma", "espacio",
  "tienda", "mercado", "dinero", "precio", "oferta",
  "trabajo", "oficina", "jefe", "colega", "proyecto",
  "idea", "plan", "meta", "reto", "logro",
  "energía", "calma", "fuerza", "paciencia", "valor",
  "bondad", "odio", "paz", "guerra", "batalla",
  "soldado", "niño", "niña", "madre", "padre",
  "hermano", "hermana", "tío", "tía", "primo",
  "abuelo", "abuela", "pareja", "novio", "novia",
  "boda", "cumpleaños", "regalo", "sorpresa", "fiesta",
  "música", "danza", "baile", "película", "serie",
  "pantalla", "luz", "cámara", "acción", "escena",
  "actor", "actriz", "director", "guión", "teatro",
  "cultura", "arte", "museo", "pintura", "escultura",
  "dibujo", "línea", "forma", "volumen", "estructura",
  "edificio", "puente", "carretera", "vehículo", "bicicleta",
  "coche", "autobús", "tren", "avión", "barco"
    ],
    pangramas: [
        "El veloz murciélago hindú comía feliz cardillo y kiwi bajo la luna llena.",
  "El rápido zorro marrón salta sobre el perro perezoso y se esconde tras el seto.",
  "Jovencillo emponzoñado de whisky: ¡qué figurota exhibe para la foto!",
  "Benjamín pidió kiwi, frambuesa y jugo de uva para la fiesta del sábado.",
  "El cadáver de Wamba, rey godo, fue exhumado y trasladado en caja de zinc.",
  "Whisky bueno: ¡excitad mi frágil pequeña vejez con jazz y blues!",
  "Exigid con brío a políticos zafios que expliquen su gestión económica.",
  "El viejo Señor Gómez pedía queso, kiwi y habas, pero le dieron jabón.",
  "El juez mandó exhumar el cadáver de Wamba con mucho sigilo y rapidez.",
  "Quedó exhausto el pingüino tras cruzar kilómetros bajo la lluvia gélida.",
  "La niña exigió hoy bizcocho, flan y kiwi para su pequeño jaguar de juguete.",
  "Blanco zorro feliz esquiva jabato, canta y duerme muy próximo al estanque.",
  "Ya que el típico whisky con jazmín logró exudar brío, venció sin piedad.",
  "El bajel rápido, con whisky y kivi, fondeó junto al muelle del zaguán.",
  "Zorras y pingüinos conviven bajo el cálido sol que mezcla brío y energía.",
  "El kiwi jugoso y barato fue comprado por Xavier en el zoco de Jaén.",
  "¡Oh, joven! Haz brillar tu equipo de fútbol con mezcla de pasión y entrega.",
  "El pingüino Wenceslao viajó en taxi por Perú y bajó feliz del jaguar azul.",
  "Mi bujía explota con gran frenesí; jazz, vodka, kárate y whisky mezclados.",
  "Zambullirse en whisky fue jugada peligrosa, dijo el joven con cara de buey.",
  "El pequeño jabalí cruzó vientos fríos y húmedos, buscando zanahorias y kiwis.",
  "Yo vi que el viejo zorro bajó feliz al pantano, mientras jugaba con su kayak.",
  "Bajo el sol de junio, Xavier jugó feliz con su pingüino mientras bebía whisky.",
  "Zulema gritó: ¡Hay bizcocho, kiwi, flan y uvas en el refrigerador, chicos!",
  "Jorge compró whisky, kiwi y bizcochos para celebrar su éxito frente al público.",
  "La foca vieja y bizca exigía jazz, whisky, pingüinos y cómics de Xavier.",
  "¡Zaz! Cayó el whisky en el piano y Julieta gritó: ¡Benjamín, haz algo ya!",
  "Katia exhibe bizarras joyas, mientras flota en su yate por el golfo de Bizkaia.",
  "El brujo Xavier mezcló kiwi, jazmín, vodka y fuego para invocar a los zombis.",
  "Yegua y buey cruzan juntos el frío zaguán mientras bizquean por el polvo.",
  "Félix jugaba con un zorro blanco, un pingüino azul y su viejo kayak japonés.",
  "Zuleika y Javier quisieron mezclar flan, kiwi y bizcocho con zumo de naranja.",
  "¿Ves? El pingüino y el zorro juegan bajo la bruma con jazz y whisky.",
  "Jacinta vio al búho feliz que cruzó el zaguán con whisky, jazz y kiwi.",
  "El jefe exigía que Wenceslao, borracho y feliz, tocara jazz con su viejo xilófono.",
  "Yo mezclo jazz y vodka para que el pingüino vuele feliz sobre el zaguán.",
  "Karla bajó del jet con su zorro de peluche, feliz por el bizcocho gratis.",
  "¡Uf! Qué zambullida tan brava dio el pingüino en whisky con kiwi y jazmín.",
  "Flotó el kayak sobre un río de vodka, mientras el zorro viejo jugaba jazz.",
  "¡Zorra joven! Di que bajaste feliz al pantano para mezclar kiwi con bizcocho.",
  "Qué joven feliz cruzó el zaguán con whisky, kiwi, bizcocho y flan en la mochila.",
  "Bajo un cielo gris, el pingüino Javier buscaba jazmín, whisky y flan de kiwi.",
  "Zulema pidió flan, bizcocho, kiwi y un jugo de uva con mezcla de vodka.",
  "Mi gato joven exige whisky, kiwi y un bizcocho cada jueves de jazz y sol.",
  "Exhausto, Javier bajó al zaguán con su pingüino en kayak tocando jazz y bebiendo whisky.",
  "Yo quiero mezclar whisky con kiwi, bizcocho y jugo de uva para el zorro feliz.",
  "Qué feliz joven pidió zambullirse en vodka con kiwi y música de jazz vibrante.",
  "Flotando en su kayak, el zorro escuchaba jazz mientras bebía whisky y mordía un kiwi.",
  "¡Zambúllete ya! gritó el joven a su amigo pingüino feliz, mientras agitaba flan y vodka.",
  "Bizcocho, kiwi, jugo de uva y whisky fueron servidos al zorro que bailaba jazz en el zaguán."
    ],
    ingles: [
        "The quick brown fox jumps over the lazy dog.",
        "Success is the sum of small efforts repeated every day.",
        "Patience and persistence make the impossible possible.",
        "Every master was once a beginner who never gave up.",
        "The only way to learn is by doing and making mistakes.",
        "Your fingers can fly when your mind is fully focused.",
        "Accuracy today builds the speed of tomorrow.",
        "A well-practiced hand outpaces a rushing mind.",
        "The keyboard is a gateway to digital expression.",
        "True skill comes from mindful repetition over time.",
        "Typing fast means nothing without precision.",
        "Small steps taken daily lead to big results.",
        "Don't fear mistakes—they're part of the process.",
        "Keep your posture straight and your mind sharper.",
        "The mind remembers, the fingers repeat.",
        "Learning to type is learning to think with your hands.",
        "Slow is smooth, and smooth becomes fast.",
        "Practice doesn't make perfect, practice makes permanent.",
        "Speed is the reward of focused consistency.",
        "Touch typing frees your thoughts from the keys.",
        "Discipline turns routine into excellence.",
        "The path to mastery is paved with patience.",
        "One letter at a time, one skill at a time.",
        "Consistency is more important than intensity.",
        "Flow happens when skill meets concentration.",
        "You type as you train—practice smart.",
        "Mistakes are proof that you're improving.",
        "A calm mind leads to fluid motion.",
        "Repetition is the foundation of speed.",
        "Train your hands, and your thoughts will follow.",
        "Typing is not just speed, it's expression.",
        "No shortcuts, just steady progress.",
        "Practice daily, improve forever.",
        "The keyboard is your playground of precision.",
        "Progress hides in the small, quiet moments.",
        "Every keystroke brings you closer to mastery.",
        "Typing fast starts with typing right.",
        "Your brain leads; your hands follow.",
        "Accuracy first, speed second.",
        "Type with purpose, not just pace.",
        "You're one session away from better typing.",
        "Skill grows where effort flows.",
        "The habit of practice creates excellence.",
        "Don't chase speed—build it.",
        "A strong foundation beats flashy fingers.",
        "Muscle memory takes time, but it pays off.",
        "Good habits lead to great results.",
        "Let your fingers learn, and your mind will rest.",
        "Fast fingers come from quiet focus.",
        "Every session matters.",
        "Even five minutes of practice counts.",
        "Type like you mean it.",
        "Mistakes are stepping stones.",
        "Every expert was once frustrated too.",
        "Typing is rhythm, not rush.",
        "Don't rush—flow.",
        "You learn to type by typing.",
        "The best typists are mindful typists.",
        "Build skills, not stress.",
        "Enjoy the process, not just the result.",
        "Calm hands, clear thoughts.",
        "Practice breeds confidence.",
        "The keyboard is your tool, not your enemy.",
        "With every word, you grow.",
        "Stay focused, stay steady.",
        "Keep typing—it gets better.",
        "Precision makes perfection possible.",
        "Don't type harder, type smarter.",
        "Control creates consistency.",
        "Balance speed with grace.",
        "Better today than yesterday.",
        "Each letter teaches something new.",
        "The journey to speed is slow at first.",
        "Good form prevents bad habits.",
        "Strong basics build solid skills.",
        "Stay patient—it's a skill worth having.",
        "Keep going—you're improving more than you think.",
        "Your only competition is your past self.",
        "One word, one win.",
        "Breathe, relax, type.",
        "Progress over perfection.",
        "You're building skill, not just words.",
        "Stay curious and keep typing.",
        "Typing is a quiet kind of power.",
        "Don't break your rhythm—build it.",
        "The keyboard is a dance of fingers.",
        "You are in control of the keys.",
        "Train your fingers to think for you.",
        "Skill comes in silence.",
        "Let go of speed—embrace flow.",
        "Comfort leads to confidence.",
        "Type with intention, not impulse.",
        "Great typists type with grace.",
        "Be patient with your progress.",
        "Every line is a lesson.",
        "Every practice builds precision.",
        "Start slow, finish strong.",
        "Let your hands learn the way.",
        "You are one session away from growth.",
        "Keep calm and keep typing.",
        "Typing is thinking through your fingers.",
        "Be present on the page.",
        "Type to express, not to impress.",
        "Small progress is still progress.",
        "Never stop learning, never stop typing."
    ],
    frances: [
        "Bonjour, comment allez-vous en ce beau matin ?",
        "La vie est une aventure à écrire jour après jour.",
        "Le succès appartient à ceux qui osent persévérer.",
        "La pratique régulière transforme les rêves en réalité.",
        "Chaque erreur est une leçon déguisée en expérience.",
        "Le clavier est un instrument, maîtrisez-le avec art.",
        "La vitesse vient naturellement avec la précision.",
        "La concentration est la clé de toute performance.",
        "Un esprit calme et des doigts agiles créent des miracles.",
        "Apprendre, c'est avancer un mot à la fois.",
        "Il n'y a pas de raccourci vers l'excellence durable.",
        "Les efforts répétés forgent les grandes compétences.",
        "La constance est plus puissante que la motivation passagère.",
        "Écrivez avec le cœur et tapez avec la tête.",
        "Chaque lettre tapée est un pas vers la maîtrise.",
        "La patience transforme les débutants en experts.",
        "Un bon typiste écoute le rythme des mots.",
        "Chaque touche compte dans le chemin du progrès.",
        "La discipline construit la confiance.",
        "Rien ne vaut une pratique consciente et régulière.",
        "Faites de chaque séance une opportunité d'apprendre.",
        "La fluidité vient avec l'expérience et l'attention.",
        "Les mains mémorisent ce que l'esprit répète.",
        "Commencez lentement, terminez rapidement.",
        "Un bon début assure une progression constante.",
        "La répétition attentive mène à la perfection.",
        "La précision aujourd'hui crée la vitesse de demain.",
        "Chaque minute de pratique compte vraiment.",
        "Taper n'est pas une course, c'est un art.",
        "Lenteur et constance gagnent la course.",
        "Les doigts entraînés libèrent l'esprit pour la pensée.",
        "Un mot après l'autre, vous devenez meilleur.",
        "Le progrès est parfois silencieux mais puissant.",
        "Taper, c'est penser avec ses mains.",
        "Le rythme de vos doigts reflète votre attention.",
        "Maîtriser le clavier, c'est libérer votre créativité.",
        "Faites confiance à vos mains et restez concentré.",
        "Même les experts ont commencé par faire des fautes.",
        "Chaque erreur est une opportunité d'amélioration.",
        "Tapez avec intention, pas avec précipitation.",
        "Le calme améliore la performance.",
        "Votre corps apprend ce que vous lui répétez.",
        "Les grandes compétences viennent des petites habitudes.",
        "Tapez moins vite, mais mieux.",
        "Le chemin vers la maîtrise commence par la répétition.",
        "Concentrez-vous sur la qualité avant la quantité.",
        "Évitez la frustration, accueillez l'apprentissage.",
        "Le clavier est votre partenaire, pas votre obstacle.",
        "Soyez patient, les résultats viendront.",
        "Vous tapez mieux que vous ne le pensez.",
        "Ne vous comparez qu'à vous-même.",
        "Un bon jour de pratique vaut mieux qu'aucun.",
        "L'apprentissage est un marathon, pas un sprint.",
        "Répétez encore et encore, jusqu'à ce que ça devienne naturel.",
        "Le succès se construit touche par touche.",
        "Chaque ligne tapée renforce votre compétence.",
        "Ne sous-estimez jamais le pouvoir de la répétition.",
        "Taper avec précision est un acte de pleine conscience.",
        "Les petits progrès s'additionnent vite.",
        "Ce qui semble difficile aujourd'hui sera facile demain.",
        "Le progrès se cache dans les détails.",
        "Écoutez le son de votre progression.",
        "L'attention est votre meilleure alliée.",
        "Construisez la confiance à travers la cohérence.",
        "Taper est une danse entre cerveau et mains.",
        "Votre posture influence vos performances.",
        "Écrire bien, c'est écrire clairement et sans erreur.",
        "Transformez la pratique en plaisir.",
        "Un esprit clair produit un texte clair.",
        "Taper est une habitude qui mène à l'expression.",
        "L'apprentissage constant est la clé de la réussite.",
        "Ne précipitez rien, respectez votre rythme.",
        "Votre clavier est un outil de puissance tranquille.",
        "Le style vient après la maîtrise.",
        "Une frappe précise vaut mieux qu'une frappe rapide.",
        "Restez calme et continuez à taper.",
        "Chaque mot bien tapé est une victoire.",
        "Vos mains savent, faites-leur confiance.",
        "Tapez lentement, mais sûrement.",
        "Construisez une base solide avant d'aller vite.",
        "La perfection n'est pas l'objectif, le progrès l'est.",
        "Continuez, même si vous êtes fatigué.",
        "Rien ne remplace la pratique régulière.",
        "Votre seule limite est votre propre doute.",
        "Chaque touche tapée est une affirmation de compétence.",
        "Soyez fier de chaque progrès.",
        "Le calme intérieur mène à la maîtrise extérieure.",
        "Visualisez votre succès, tapez pour y arriver.",
        "L'automatisme vient avec la répétition.",
        "Rendez chaque séance unique et productive.",
        "Tapez comme si vous écriviez votre histoire.",
        "Vos progrès sont le fruit de votre persévérance.",
        "La maîtrise naît de l'intention constante.",
        "Un pas à la fois, une touche à la fois.",
        "Même les erreurs ont une valeur.",
        "Ralentir, c'est parfois avancer plus vite.",
        "Soyez l'auteur de votre propre progression.",
        "Continuez à apprendre, continuez à taper.",
        "Votre clavier vous attend. Ne le faites pas attendre.",
        "Taper est une forme de méditation productive.",
        "Vous êtes plus proche de la maîtrise que vous ne le pensez.",
        "Avec chaque mot, vous vous rapprochez de l'excellence.",
        "Il suffit de commencer, et ne pas s'arrêter."
    ],
    frasesConNumeros: [
        "Compré 5 manzanas, 3 plátanos y 2 litros de leche.",
        "El evento será el 15/11/2023 en el auditorio 7 a las 19:30.",
        "Mi abuela cumplió 95 años con una salud de hierro.",
        "El 78% de los participantes mejoraron su velocidad en 2 semanas.",
        "La receta necesita 250g de harina y 100ml de aceite.",
        "El vuelo 402 despega a las 06:45 desde la puerta 12B.",
        "El 99% de los errores se corrigen con atención al detalle.",
        "El código postal 28015 corresponde al centro de la ciudad.",
        "El 50% de descuento aplica hasta el 30 de septiembre.",
        "El edificio tiene 24 pisos y 3 ascensores modernos.",
        "El número de emergencia es 112 en toda Europa.",
        "Reservé mesa para 4 personas a las 21:00.",
        "Han pasado 10 años desde aquel viaje inolvidable.",
        "El niño tiene 8 años y ya sabe programar.",
        "Mi contraseña contiene 12 caracteres alfanuméricos.",
        "La carrera es de 10 kilómetros con 3 estaciones de agua.",
        "Solo quedan 2 entradas para el concierto del 22 de abril.",
        "Hay un 35% de probabilidades de lluvia este fin de semana.",
        "La reunión empieza a las 14:45 y termina a las 16:00.",
        "Necesito 1 taza de azúcar y 2 de harina.",
        "La distancia entre ambas ciudades es de 732 km.",
        "El 7 es considerado un número de la suerte.",
        "Este tren llega a las 18:10 y parte a las 18:25.",
        "Mi DNI termina en 5093 y empieza por 28.",
        "Hay 31 días en el mes de enero.",
        "He leído 18 libros en lo que va del año.",
        "Faltan 13 días para mi cumpleaños.",
        "La película empieza a las 20:30 en la sala 4.",
        "Mi padre nació en 1964, en plena década prodigiosa.",
        "Vendimos 120 productos en las primeras 24 horas.",
        "El examen tiene 40 preguntas en total.",
        "Pagué 37,50 € por el billete de tren.",
        "Mi hermano pesa 72 kg y mide 1,80 m.",
        "Recibí 47 correos electrónicos esta mañana.",
        "La temperatura llegó a 0°C durante la madrugada.",
        "Este año hemos plantado 300 árboles nuevos.",
        "La oferta termina el 31/12/2025 a las 23:59.",
        "Hay 11 jugadores en un equipo de fútbol.",
        "Solo necesitas 6 minutos para completar este ejercicio.",
        "Mi coche consume 5,2 litros cada 100 km.",
        "Hoy es el día 127 del año.",
        "El número pi es aproximadamente 3,1416.",
        "Este documento tiene 14 páginas impresas.",
        "La llamada duró 17 minutos y 22 segundos.",
        "Tengo una colección de 92 monedas distintas.",
        "Viajamos por 9 países en 30 días.",
        "La batería está al 84% de carga.",
        "Este software fue actualizado el 02/03/2024.",
        "El edificio fue construido en 1928.",
        "Su salario aumentó un 12% este trimestre.",
        "La habitación mide 4,5 metros de ancho por 6 de largo.",
        "El video tiene 1.204 visualizaciones y 78 comentarios.",
        "Guardé 8 archivos en la carpeta 'Proyectos 2025'.",
        "El número de serie es AB-9042-887X.",
        "El metro pasa cada 10 minutos entre semana.",
        "La clase comienza a las 13:15 en el aula 9.",
        "Se vendieron 950 entradas en menos de 6 horas.",
        "Hicimos 3 pausas durante el trayecto de 7 horas.",
        "El 15% de los encuestados prefirió la opción B.",
        "El reloj marcaba las 12:34 cuando salí.",
        "Hay 5 tareas pendientes en la lista de hoy.",
        "El televisor mide 55 pulgadas y pesa 17 kg.",
        "Ese archivo ocupa 2,3 GB en el disco duro.",
        "Reservaron 2 habitaciones dobles para el 14 de mayo.",
        "Mi hermana nació el 04/07/2001 a las 03:42.",
        "El tren número 2192 parte a las 11:50.",
        "El ascensor sube a 3 metros por segundo.",
        "Necesitas 7 intentos para desbloquear el nivel.",
        "Hay 42 escalones entre el sótano y la azotea.",
        "Conté 29 estrellas fugaces en una sola noche.",
        "El partido terminó 3 a 2 en tiempo extra.",
        "El archivo fue creado el 28/08/2023 a las 08:00.",
        "Cada caja contiene 36 unidades de producto.",
        "El examen tiene una duración de 90 minutos.",
        "La carrera comenzó a las 07:00 en punto.",
        "El promedio fue de 8,5 sobre 10.",
        "En total, donaron 1.500 € a la fundación.",
        "El mes pasado llovió durante 19 días.",
        "Mi reloj marca las 22:47 exactamente.",
        "Debes recorrer 1,2 kilómetros más para llegar.",
        "Tardé 2 horas y 45 minutos en terminarlo.",
        "El código de acceso es 4296.",
        "La factura llegó el día 12 del mes.",
        "Pagamos 89,99 € por la suscripción anual.",
        "Subimos 10 pisos por las escaleras.",
        "Ese modelo tiene una resolución de 3840 x 2160.",
        "Se registraron 27 grados a la sombra.",
        "Llegué a casa a las 18:19 sin contratiempos.",
        "Mi peso ideal es de 68 kilogramos.",
        "El motor tiene una potencia de 180 CV.",
        "Ese puente mide 1.343 metros de largo.",
        "Hubo 4 accidentes leves en la autopista 6.",
        "Esta app tiene una nota de 4,7 sobre 5.",
        "La oferta termina en 1 hora y 20 minutos.",
        "El 100% de los asistentes firmó el acuerdo.",
        "Conté 300 palabras en ese artículo.",
        "La casa tiene 2 plantas y 5 habitaciones.",
        "Me levanté a las 06:00 todos los días esta semana.",
        "Faltan 60 segundos para que empiece.",
        "Se necesitan 15 días hábiles para procesarlo.",
        "El juego fue lanzado el 10/10/2020.",
        "La última actualización fue hace 48 horas.",
        "Este teclado tiene 104 teclas activas.",
        "El libro cuesta 19,95 € en promoción."
    ],
    frasesConSimbolos: [
        "¿Cuál es tu contraseña? ¡Dímela ahora! ¡Vamos!",
        "La ruta del archivo es: C:\\Archivos\\Proyecto\\final.docx",
        "El correo fue enviado a: maria.garcia@empresa.com",
        "El archivo se llama informe_v3.1.4-final+resumen.pdf",
        "Presiona Ctrl+Alt+Supr para reiniciar el sistema.",
        "¡Oferta exclusiva! Sólo hoy: ¡50% de descuento en todo!",
        "Para salir, escribe: /salir o pulsa ESC.",
        "El código es: #CONFIDENCIAL; no lo compartas.",
        "Archivo movido a ~/Documentos/proyectos/2025/",
        "Los símbolos que puedes usar son: &, %, $, #, @ y *.",
        "El campo 'usuario' no puede estar vacío: ¡rellénalo!",
        "Comando ejecutado: sudo apt-get install python3.12",
        "No olvides añadir `;` al final de cada línea en C.",
        "Tu ID de sesión es: A9f_87~Kd#v|T3$1",
        "Los corchetes [ ] y las llaves { } deben cerrarse.",
        "Símbolos comunes: (paréntesis), {llaves}, [corchetes]",
        "¡Importante! Guarda el archivo como: datos_finales_2025.csv",
        "El formato es: nombre:valor; separado por punto y coma.",
        "Atajo rápido: Alt+F4 para cerrar la ventana actual.",
        "Dirección IP: 192.168.1.1 - acceso restringido.",
        "Debes completar los campos marcados con * (obligatorio).",
        "Sigue la estructura: función(parametro1, parametro2);",
        "Para formatear usa: `negrita`, *cursiva*, ~tachado~",
        "URL válida: https://www.mi-sitio.com/acceso?code=abc123",
        "El sistema respondió con: !ERROR_FATAL: código 77.",
        "Incluye el símbolo € en el reporte de precios.",
        "Haz clic en 'Aceptar' o pulsa la tecla Enter.",
        "Datos confidenciales almacenados en backup@servidor.local",
        "Ruta Unix: /usr/bin/python3.10/config/",
        "Utiliza el símbolo ¬ para marcar campos omitidos.",
        "El archivo fue guardado como: backup_03-05-2025.zip",
        "Tu clave temporal es: K9*2$~dC`#@2025!",
        "Aviso: archivo corrupto · intenta una restauración.",
        "Usa || para separar condiciones múltiples en el código.",
        "Comando inválido: bash: syntax error near unexpected token `)'",
        "Este campo acepta símbolos como !, @, #, $, %, &, * y más.",
        "Inserta la etiqueta <meta charset='UTF-8'> en el <head>.",
        "Ejecuta el script: ./iniciar.sh > salida.log 2>&1",
        "Tu nuevo usuario es: user_test@correo.com; cambia la clave.",
        "Variables: €precio, ¬activo, @usuario, #clave, &estado",
        "Para comandos múltiples usa `&&` entre ellos.",
        "Este caracter ` (acento grave) no es lo mismo que ' (apóstrofe)",
        "Para comentarios en Python se usa #: # esto es un comentario",
        "El símbolo ª se usa para indicar número ordinal femenino.",
        "Configura el path en Windows como: %USERPROFILE%\\AppData\\Local",
        "Marca las secciones usando ===== encabezado =====",
        "El símbolo | (barra vertical) representa un OR lógico.",
        "¿Listo? Entonces ejecuta: ./configurar.sh && ./lanzar.sh"
    ],
    codigoPython: [
        "# Hola Mundo en Python\nprint('¡Hola, mundo!')",

        "# Importar módulo random\nimport random\nnumero = random.randint(1, 100)\nprint(f\"Número aleatorio: {numero}\")",
    
        "# Función simple para sumar dos números\ndef suma(a, b):\n    return a + b\nprint(\"Resultado:\", suma(5, 3))",
    
        "# Bucle for sobre una lista\nanimales = [\"gato\", \"perro\", \"ratón\"]\nfor animal in animales:\n    print(animal)",
    
        "# Bucle while con condición\ncontador = 0\nwhile contador < 5:\n    print(\"Contador:\", contador)\n    contador += 1",
    
        "# Condicional if-elif-else\nx = 10\nif x > 10:\n    print(\"Mayor que 10\")\nelif x == 10:\n    print(\"Igual a 10\")\nelse:\n    print(\"Menor que 10\")",
    
        "# Función con parámetro por defecto\ndef saludar(nombre=\"amigo\"):\n    print(f\"Hola, {nombre}!\")\nsaludar()\nsaludar(\"Lucía\")",
    
        "# Diccionario y recorrido con items()\npersona = {\"nombre\": \"Ana\", \"edad\": 25}\nfor clave, valor in persona.items():\n    print(f\"{clave}: {valor}\")",
    
        "# Lista por comprensión\npares = [x for x in range(20) if x % 2 == 0]\nprint(pares)",
    
        "# Definir y usar una clase\nclass Persona:\n    def __init__(self, nombre):\n        self.nombre = nombre\n    def saludar(self):\n        print(f\"Hola, soy {self.nombre}\")\np = Persona(\"Luis\")\np.saludar()",
    
        "# Manejo de errores con try-except\ntry:\n    numero = int(\"abc\")\nexcept ValueError:\n    print(\"Error: No es un número válido.\")",
    
        "# Función recursiva para factorial\ndef factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\nprint(factorial(5))",
    
        "# Uso de sets para eliminar duplicados\nnumeros = [1, 2, 2, 3, 4, 4]\nunicos = set(numeros)\nprint(unicos)",
    
        "# Función lambda\ncuadrado = lambda x: x**2\nprint(cuadrado(7))",
    
        "# Map y lambda juntos\nnumeros = [1, 2, 3]\ncuadrados = list(map(lambda x: x**2, numeros))\nprint(cuadrados)",
    
        "# Filtrar una lista con filter\nnumeros = [5, 10, 15, 20]\nmayores = list(filter(lambda x: x > 10, numeros))\nprint(mayores)",
    
        "# Función que devuelve otra función\ndef multiplicador(factor):\n    return lambda x: x * factor\ndoblar = multiplicador(2)\nprint(doblar(5))",
    
        "# Uso básico de f-strings\nnombre = \"Carlos\"\nprint(f\"Hola, {nombre}!\")",
    
        "# Leer un archivo línea por línea\nwith open(\"archivo.txt\", \"r\") as archivo:\n    for linea in archivo:\n        print(linea.strip())",
    
        "# Escribir en un archivo\nwith open(\"salida.txt\", \"w\") as archivo:\n    archivo.write(\"Este es un archivo de salida.\\n\")",
    
        "# Enumerate para contar elementos\nelementos = [\"a\", \"b\", \"c\"]\nfor i, val in enumerate(elementos):\n    print(f\"Índice {i}: {val}\")",
    
        "# Zipping dos listas\nnombres = [\"Ana\", \"Luis\"]\nedades = [25, 30]\nfor nombre, edad in zip(nombres, edades):\n    print(f\"{nombre} tiene {edad} años\")",
    
        "# Unpacking de tuplas\npunto = (3, 4)\nx, y = punto\nprint(x, y)",
    
        "# Uso de assert para pruebas\nassert 2 + 2 == 4\nprint(\"Todo correcto\")",
    
        "# Crear una lista de listas\nmatriz = [[1, 2], [3, 4]]\nfor fila in matriz:\n    print(fila)",
    
        "# Modificar una lista mientras se recorre\nnumeros = [1, 2, 3, 4]\nnumeros = [x * 2 for x in numeros]\nprint(numeros)",
    
        "# String methods\ntxt = \"  Hola Mundo  \"\nprint(txt.strip().upper().replace(\" \", \"_\"))",
    
        "# Crear un diccionario con dict comprehension\ncuadrados = {x: x*x for x in range(5)}\nprint(cuadrados)",
    
        "# Generador con yield\ndef generador():\n    for i in range(3):\n        yield i\nfor valor in generador():\n    print(valor)",
    
        "# Aplanar lista de listas\nlistas = [[1,2],[3,4]]\nplana = [item for sublista in listas for item in sublista]\nprint(plana)",
    
        "# Comprobar si un string contiene un substring\nmensaje = \"Bienvenido a Python\"\nprint(\"Python\" in mensaje)",
    
        "# Invertir una cadena\ntexto = \"Python\"\nprint(texto[::-1])" ]
};

// Mantener quotes original para compatibilidad
export const quotes = [
    ...quotesCategories.simple,
    ...quotesCategories.compleja
];
